import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Open_Sans } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/layout/SideBar";
import Nav from "@/components/layout/Nav";
import { ChartProvider } from "@/components/layout/charts/ChartProvider";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body
        className={`${plusJakartaSans.variable} ${openSans.variable} antialiased flex flex-col min-h-screen`}
      >
        <div className="flex pl-65">
          <SideBar />
          <div className="flex-1">
            <Nav />
            <ChartProvider>{children}</ChartProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
